name: Push

on:
  push:
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    environment: Production
      - ADD_1=1
    steps:
      - uses: actions/checkout@v1
      # - name: Set env
      #   run:
      - name: Log into Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to GitHub Package Registry
        run: make push VERSION=$(echo ${GITHUB_REF:10})
