name: Push

on:
  push:
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      Production
      # - ${{vars.RELEASE_VERSION}}=${GITHUB_REF:10}
    steps:
      - uses: actions/checkout@v1
      # - name: Set env
      #   run: echo "${{vars.RELEASE_VERSION}}=$(echo ${GITHUB_REF:10})"
      - name: Log into Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to GitHub Package Registry
        run: echo "make push VERSION=$(echo ${GITHUB_REF:10})"
